In [1]:
pip install plotly

Collecting plotly
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: narwhals>=1.15.1 in /Users/kaliprasad/Documents/MACHINE_LEARNING/pizza_env/lib/python3.14/site-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in /Users/kaliprasad/Documents/MACHINE_LEARNING/pizza_env/lib/python3.14/site-packages (from plotly) (26.2)
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 51.4 MB/s  0:00:00 eta 0:00:01
Installing collected packages: plotly
Successfully installed plotly-6.9.0

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install --upgrade pip

Requirement already satisfied: pip in /Users/kaliprasad/Documents/MACHINE_LEARNING/pizza_env/lib/python3.14/site-packages (26.0.1)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 25.4 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.0.1
    Uninstalling pip-26.0.1:
      Successfully uninstalled pip-26.0.1
Successfully installed pip-26.2.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
import plotly.express as px
import plotly.graph_objects as go

In [8]:
tips = px.data.tips()
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
df = px.data.gapminder().query("country=='India'")
df.head()

    country continent  year  lifeExp        pop   gdpPercap iso_alpha  iso_num
696   India      Asia  1952   37.373  372000000  546.565749       IND      356
697   India      Asia  1957   40.249  409000000  590.061996       IND      356
698   India      Asia  1962   43.605  454000000  658.347151       IND      356
699   India      Asia  1967   47.193  506000000  700.770611       IND      356
700   India      Asia  1972   50.651  567000000  724.032527       IND      356

In [10]:
fig = px.line(df, x="year",y="lifeExp")
fig.show()

In [11]:
fig = px.line(
 df,
 x="year",
 y="lifeExp",
 markers=True
)
fig.show()

In [12]:
fig = px.line(
 df,
 x="year",
 y="lifeExp",
 title="Life Expectancy of India"
)
fig.show()

In [13]:
fig = px.scatter(
 tips,
 x="total_bill",
 y="tip"
)
fig.show()

In [14]:
fig = px.scatter(
 tips,
 x="total_bill",
 y="tip",
 color="sex"
)
fig.show()

In [15]:
fig = px.scatter(
 tips,
 x="total_bill",
 y="tip",
 size="size"
)
fig.show()

In [16]:
fig = px.bar(
 tips,
 x="day",
 y="total_bill"
)
fig.show()

In [17]:
fig = px.bar(
 tips,
 x="day",
 y="total_bill",
 color="sex"
)
fig.show()

In [19]:
fig = px.bar(
 tips,
 x="total_bill",
 y="day",
 orientation="h"
)
fig.show()